trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 6.x

- script: dotnet restore

- script: dotnet build -c $(buildConfiguration) -v minimal --no-restore

- script: dotnet test -c $(buildConfiguration) -v normal --no-build

- script: dotnet pack -c Release --version-suffix ci-$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory) --include-symbols --verbosity minimal --no-build